######################################################################
# Automatically generated by qmake (2.01a) Thu May 28 16:44:38 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += myqtapp.h
FORMS += myqtapp.ui
SOURCES += main.cc myqtapp.cc
