######################################################################
# Automatically generated by qmake (2.01a) Thu May 28 10:11:53 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += sample.cc
