######################################################################
# Automatically generated by qmake (2.01a) Mon May 31 09:42:20 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += politic.h
FORMS += politic.ui
SOURCES += main.cpp politic.cpp
