######################################################################
# Automatically generated by qmake (2.01a) Mon Jun 29 21:40:37 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += CannonField.h myWidget.h
SOURCES += CannonField.cpp main.cpp myWidget.cpp
