######################################################################
# Automatically generated by qmake (2.01a) Thu May 28 19:37:40 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += slider.h
FORMS += SimpleDialog.ui
SOURCES += main.cc slider.cc
